<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="12664" started-at="2019-01-22T08:44:59Z" finished-at="2019-01-22T08:45:11Z">
    <groups>
      <group name="Sanity">
        <method signature="HomePageTests.verifyLogo()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyLogo" class="com.app.tests.HomePageTests"/>
        <method signature="HomePageTests.verifyMenuNavigation()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyMenuNavigation" class="com.app.tests.HomePageTests"/>
        <method signature="HomePageTests.verifyNavTitles()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyNavTitles" class="com.app.tests.HomePageTests"/>
        <method signature="HomePageTests.verifyNewsletterInputAlert()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyNewsletterInputAlert" class="com.app.tests.HomePageTests"/>
      </group> <!-- Sanity -->
    </groups>
    <test name="Test" duration-ms="12664" started-at="2019-01-22T08:44:59Z" finished-at="2019-01-22T08:45:11Z">
      <class name="com.app.tests.HomePageTests">
        <test-method status="PASS" signature="verifyLogo()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyLogo" duration-ms="53" started-at="2019-01-22T08:44:59Z" finished-at="2019-01-22T08:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogo -->
        <test-method status="PASS" signature="verifyMenuNavigation()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyMenuNavigation" duration-ms="9161" started-at="2019-01-22T08:44:59Z" finished-at="2019-01-22T08:45:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMenuNavigation -->
        <test-method status="SKIP" signature="verifyNavTitles()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyNavTitles" duration-ms="142" started-at="2019-01-22T08:45:08Z" finished-at="2019-01-22T08:45:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed: T-Shirts page is not displayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed: T-Shirts page is not displayed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at com.app.tests.HomePageTests.verifyNavTitles(HomePageTests.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNavTitles -->
        <test-method status="SKIP" signature="verifyNavTitles()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyNavTitles" duration-ms="119" started-at="2019-01-22T08:45:08Z" finished-at="2019-01-22T08:45:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed: T-Shirts page is not displayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed: T-Shirts page is not displayed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at com.app.tests.HomePageTests.verifyNavTitles(HomePageTests.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNavTitles -->
        <test-method status="FAIL" signature="verifyNavTitles()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyNavTitles" duration-ms="121" started-at="2019-01-22T08:45:08Z" finished-at="2019-01-22T08:45:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed: T-Shirts page is not displayed expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed: T-Shirts page is not displayed expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at com.app.tests.HomePageTests.verifyNavTitles(HomePageTests.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNavTitles -->
        <test-method status="PASS" signature="verifyNewsletterInputAlert()[pri:0, instance:com.app.tests.HomePageTests@5890e879]" name="verifyNewsletterInputAlert" duration-ms="3029" started-at="2019-01-22T08:45:08Z" finished-at="2019-01-22T08:45:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNewsletterInputAlert -->
      </class> <!-- com.app.tests.HomePageTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
